CC=fteqcc64
CFLAGS=-Wall -O3


all: progs.dat


progs.dat: $(wildcard qc/*.qc) ./qc/progs.src
	$(CC) $(CFLAGS) -srcfile qc/progs.src

tga2spr:
	$(CC) tools/tga2spr.c -o tga2spr

.PHONY: all


# PAK0
# progs/plane1.mdl
# progs/plane1b.mdl
# progs/plane2.mdl
# progs/plane2b.mdl
# progs/plane3.mdl
# progs/plane3b.mdl
# progs/plane4.mdl
# progs/plane4b.mdl
# progs/plane5.mdl
# progs/plane5b.mdl
# progs/helo1.mdl
# progs/helo1b.mdl
# progs/rocket1.mdl
# progs/rocket2.mdl
# progs/sider.mdl
# progs/sting.mdl
# progs/amraam.mdl
# progs/maver.mdl
# progs/imaver.mdl
# progs/hfire.mdl
# progs/bomb.mdl
# progs/pave.mdl
# progs/rcbo.mdl
# progs/mine.mdl
# progs/bullet.mdl
# progs/pbullet.mdl
# progs/box1.mdl
# progs/samba.mdl
# progs/samtb.mdl
# progs/aagba.mdl
# progs/aagtb.mdl
# progs/amgba.mdl
# progs/amgtb.mdl
# progs/radba.mdl
# progs/radpl.mdl
# progs/msamba.mdl
# progs/msamtb.mdl
# progs/tankba.mdl
# progs/tanktr.mdl
# progs/tanktb.mdl
# progs/humba.mdl
# progs/humtr.mdl
# progs/humtb.mdl
# progs/hovba.mdl
# progs/hovtr.mdl
# progs/hovtb.mdl
# progs/v_sider.mdl
# progs/v_sting.mdl
# progs/v_maver.mdl
# progs/v_bomb.mdl
# progs/v_mine.mdl
# progs/v_sam.mdl
# progs/v_plas.mdl
# progs/v_auto.mdl
# progs/v_cann.mdl
# progs/v_rock.mdl
# progs/v_rcbo.mdl
# progs/v_hell.mdl
# progs/v_pave.mdl
# progs/v_amra.mdl
# progs/lamp.mdl
# progs/player.mdl
# progs/null.spr
# progs/s_plasma.spr
# progs/s_target.spr
# sound/dsfirxpl.wav
# sound/dsplasma.wav
# sound/autocann.wav
# sound/rocklnch.wav
# sound/touchdwn.wav
# sound/in1.wav
# sound/in2.wav
# sound/engines/car0.wav
# sound/engines/car1.wav
# sound/engines/car2.wav
# sound/engines/car3.wav
# sound/engines/car4.wav
# sound/engines/car5.wav
# sound/engines/car6.wav
# sound/engines/car7.wav
# sound/engines/car8.wav
# sound/engines/hov0.wav
# sound/engines/hov1.wav
# sound/engines/hov2.wav
# sound/engines/hov3.wav
# sound/engines/hov4.wav
# sound/engines/hov5.wav
# sound/engines/hov6.wav
# sound/engines/hov7.wav
# sound/engines/hov8.wav
# sound/engines/tank0.wav
# sound/engines/tank1.wav
# sound/engines/tank2.wav
# sound/engines/tank3.wav
# sound/engines/tank4.wav
# sound/engines/tank5.wav
# sound/engines/tank6.wav
# sound/engines/tank7.wav
# sound/engines/tank8.wav
# sound/engines/jet0.wav
# sound/engines/jet1.wav
# sound/engines/jet2.wav
# sound/engines/jet3.wav
# sound/engines/jet4.wav
# sound/engines/jet5.wav
# sound/engines/jet6.wav
# sound/engines/jet7.wav
# sound/engines/jet8.wav
# sound/engines/chopper.wav
# sound/speech/mc_1.wav
# sound/speech/mc_2.wav
# sound/speech/mc_3.wav
# sound/speech/mc_4.wav
# sound/speech/mc_5.wav
# sound/speech/mc_6.wav
# sound/speech/mc_7.wav
# sound/speech/f2_a.wav
# sound/speech/f2_b.wav
# sound/speech/f2_c.wav
# sound/speech/f2_d.wav
# sound/speech/f2_e.wav
# sound/speech/f2_f.wav
# sound/speech/f2_g.wav
# sound/speech/f3_a.wav
# sound/speech/f3_b.wav
# sound/speech/f3_c.wav
# sound/speech/f3_d.wav
# sound/speech/f3_e.wav
# sound/speech/f3_f.wav
# sound/speech/f3_g.wav
# sound/speech/f4_a.wav
# sound/speech/f4_b.wav
# sound/speech/f4_c.wav
# sound/speech/f4_d.wav
# sound/speech/f4_e.wav
# sound/speech/f4_f.wav
# sound/speech/f4_g.wav
# sound/speech/f5_a.wav
# sound/speech/f5_b.wav
# sound/speech/f5_d.wav
# sound/speech/f5_e.wav
# sound/speech/f5_f.wav
# sound/speech/f5_g.wav
# sound/speech/f6_a.wav
# sound/speech/f6_b.wav
# sound/speech/f6_c.wav
# sound/speech/f6_d.wav
# sound/speech/f6_e.wav
# sound/speech/f6_f.wav
# sound/speech/f6_g.wav
# sound/speech/f7_a.wav
# sound/speech/f7_b.wav
# sound/speech/f7_c.wav
# sound/speech/f7_d.wav
# sound/speech/f7_f.wav
# sound/speech/f7_g.wav
# sound/speech/f8_a.wav
# sound/speech/f8_b.wav
# sound/speech/f8_c.wav
# sound/speech/f8_d.wav
# sound/speech/f8_e.wav
# sound/speech/f8_f.wav
# sound/speech/fc_1.wav
# sound/speech/fc_2.wav
# sound/speech/fc_3.wav
# sound/speech/fc_4.wav
# sound/speech/vh_mslw2.wav
# sound/speech/vh_mslw.wav
# sound/speech/rw_a_al.wav
# sound/speech/rw_a_al2.wav
# sound/speech/f7_e.wav
# sound/speech/f5_c.wav
# demo1.dem
# demo2.dem
# demo3.dem
# gfx/conback.lmp

# PAK1
# maps/air1.bsp
# maps/air2.bsp
# maps/air3.bsp
# maps/aircity.bsp
